### ISSUE TITLE
Request to https://stars-app.renci.org timed out after 300000 ms

### ISSUE THREAD

**Issue by CaseyTa** [TranslatorSRI/ontology-kp#104]
This query: 
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "a": {
          "ids": [
            "DRUGBANK:DB00215",
            "DRUGBANK:DB01175",
            "DRUGBANK:DB00472",
            "DRUGBANK:DB00176",
            "DRUGBANK:DB00715",
            "DRUGBANK:DB01104"
          ]
        },
        "b": {
          "categories": [
            "biolink:ChemicalSubstance"
          ]
        }
      },
      "edges": {
        "ab": {
          "subject": "b",
          "object": "a",
          "predicate": "biolink:subclass_of"
        }
      }
    }
  }
}
```

produces the following response after 5 minutes:
`Request to https://stars-app.renci.org timed out after 300000 ms`

**Comment by balhoff** [comment]
Sorry I missed this yesterday. I'll take a look at what the generated query looks like for this. If it could give you an answer, it would be empty (we don't have DRUGBANK). But I think somehow it's being forced to do some kind of exhaustive search to find that out.

**Comment by CaseyTa** [comment]
Hi Jim @balhoff, no worries! It may be related to the entire category of `biolink:ChemicalSubstance` rather than DRUGBANK. I'm having the same issue with the query from today's standup. Here's the message we're sending to Ontology KP that's also timing out:

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "a": {
          "ids": [
            "PUBCHEM.COMPOUND:3672",
            "PUBCHEM.COMPOUND:1983"
          ]
        },
        "b": {
          "categories": [
            "biolink:ChemicalSubstance"
          ]
        }
      },
      "edges": {
        "ab": {
          "subject": "b",
          "object": "a",
          "predicate": "biolink:subclass_of"
        }
      }
    }
  }
}
```

**Comment by cbizon** [comment]
As a KP, the ontology KP is not handling identifier conversions.  So if you want to call it for chemicals, you have to convert into chebis (that's really the only chemical vocab that's a proper ontology anyway, I think).  

We made a quick and dirty implementation of this at the relay in this notebook: https://github.com/NCATSTranslator/TranslatorArchitecture/blob/master/Notebooks/Using%20OntologyKP%20to%20get%20subclasses.ipynb

In that example, we converted DOID->MONDO before going to Ontology KP, but the principle is the same.

@balhoff does it make any sense to include that kind of transformation on the ontology KP side?

**Comment by CaseyTa** [comment]
Thanks, @cbizon. I manually did a test and used Node Normalizer to convert those Pubchem Compounds to CHEBIs, but it still seems to be hanging for me. 

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "a": {
          "ids": [
            "CHEBI:5855",
            "CHEBI:46195"
          ]
        },
        "b": {
          "categories": [
            "biolink:ChemicalSubstance"
          ]
        }
      },
      "edges": {
        "ab": {
          "subject": "b",
          "object": "a",
          "predicate": "biolink:subclass_of"
        }
      }
    }
  }
}
```

Please let me know if there's something else we may be doing wrong. I'm happy to fix this on our end if this is our issue.

**Comment by cbizon** [comment]
Hmm, well that oughta work :)
