### ISSUE TITLE
Error retrieving subclasses from OntologyKP

### ISSUE THREAD

**Issue by CaseyTa** [TranslatorSRI/ontology-kp#201]
Query: 
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "a": {
          "ids": ["MONDO:0005015"]
        },
        "b": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        }
      },
      "edges": {
        "ab": {
          "subject": "b",
          "object": "a",
          "predicate": "biolink:subclass_of"
        }
      }
    }
  }
}
```

Submitted to `https://ontology-kp.apps.renci.org/query`

Currently receiving: `Error connecting to http://ubergraph-service.balhoff.svc.cluster.local using address ubergraph-service.balhoff.svc.cluster.local:80 (unresolved: false)`

**Comment by balhoff** [comment]
Sorry @CaseyTa, there was a configuration problem which should be fixed now.
