### ISSUE TITLE
SRI Technical Debt: Ontology-KP Repo

### ISSUE THREAD

**Issue by tursynay** [TranslatorSRI/ontology-kp#330]
Hi @balhoff and @cbizon, not sure if this repo is used anymore, does not look like much has happened here in a while. As part of the Translator priority for Technical Debt, I am creating this issue to determine what needs to happen to this repo> There are 27 PRs and 5 issues, please advise:

- [ ] Determine if this repo needs to be kept or archived
- [ ] Resolve PRs if to be kept
- [ ] Update Documentation if to be kept
- [ ] Any bug fixes?

**Comment by balhoff** [comment]
Hi @tursynay, we can archive this repo.
