### ISSUE TITLE
update openapi yaml

### ISSUE THREAD

**Issue by balhoff** [TranslatorSRI/ontology-kp#38]
The "x-translator/teams" element is currently "SRI" but it should be "Standards Reference Implementation Team".

**Comment by colleenXu** [comment]
The element should also be a one-element list. So the part of the JSON would look roughly like this below:

"x-translator": {"component": "KP",
                         "teams": ["Standards Reference Implementation Team"]}

note: this string vs one-element list issue is also occurring with the CAM KP API's smartapi file.
