### ISSUE TITLE
Missing predicates?

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/ontology-kp#68]
For the ontology kp, I wanted to look see if Increased Urinary Glycerol (HP:0040301) was linked to Glycerol (CHEBI:17754) So I ran this query:
{
    "message": {
        "query_graph": {
            "nodes": {
                "a": {
                    "id": "HP:0040301"
                },
                "b": {
                    "category": "biolink:NamedThing"
                }
            },
            "edges": {
                "ab": {
                    "subject": "a",
                    "object": "b"
                }
            }
        }}}

I went with Named Thing because I didn't think that ontology kp is using biolink categories for chebis.  Lo and behold I do get an edge!

'2c42ec9b7ac8d1c994ca8cce030e30f0e8167574': {'subject': 'HP:0040301',
     'object': 'CHEBI:17754'},

However, there's no predicate on the edge.

**Comment by balhoff** [comment]
Oh, yes, I saw this recently. Actually I thought I opened an issue but must have forgotten, so I'm glad you posted this.

**Comment by balhoff** [comment]
Fixed by #98.
